# CI Workflow for checking validity of code
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main repo
        uses: actions/checkout@v3
      - name: Run ESLint
        run: |
          npm install eslint
          npx eslint --ext .js ./source/
