name: Guideline Verification
on: [pull_request, push]
jobs:
  guideline-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0   #checking only changes of this commit (not comparing previous commits)
      - name: Verify Template files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            ./source/html/template.html
            ./source/css/styles.css

      - name: Check Template Changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: echo "Template files have been modified, validate this PR/Push iff it is for error correction" exit 1
      
      - name: Get Modified Directories
        id: changed-file-dir-names
        uses: tj-actions/changed-files@v34.4.0
        with: 
          dir_names: "true"

      - name: Check that only source files changed
        run: |
          for directory in ${{ steps.changed-file-dir-names.outputs.all_changed_files }}; do
            if [[ $directory != "source"* ]] 
            then
              echo "Non-source file has been modified, manually validate PR/Push" 
              exit 1
            fi 
          done


    
