name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ESLint
        run: npm install eslint
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
